# Quick Start
# $ docker compose -f compose.talker.yaml up

services:

  ros-master:
    image: ros:noetic-ros-core
    network_mode: service:husarnet-talker
    tty: true
    environment:
      - ROS_IPV6=on
    command: stdbuf -o L roscore

  talker1:
    build: .
    network_mode: service:husarnet-talker
    tty: true
    environment:
      - ROS_IPV6=on
      - ROS_MASTER_URI=http://talker-host:11311
      - ROS_HOSTNAME=talker-host
    command: rosrun roscpp_tutorials talker

  talker2:
    build: .
    network_mode: service:husarnet-talker
    tty: true
    environment:
      - ROS_IPV6=on
      - ROS_MASTER_URI=http://talker-host:11311
      - ROS_HOSTNAME=talker-host
    command: bash -c "sleep 10 && rosrun roscpp_tutorials talker __name:=talker2"

  husarnet-talker:
    image: husarnet/husarnet
    volumes:
      - /var/lib/husarnet
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0 
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - HOSTNAME=talker-host
      - JOINCODE=${HUSARNET_JOINCODE}