# Quick Start
# $ docker compose -f compose.talker.yaml up

services:

  ros-master:
    image: ros:noetic-ros-core
    network_mode: service:husarnet-talker
    environment:
      - ROS_MASTER_URI=http://master:11311
      - ROS_HOSTNAME=master
      - ROS_IPV6=on
    command: stdbuf -o L roscore

  talker:
    build: .
    network_mode: service:husarnet-talker
    tty: true
    environment:
      - ROS_MASTER_URI=http://master:11311
      - ROS_HOSTNAME=master
      - ROS_IPV6=on
    command: rosrun roscpp_tutorials talker

  husarnet-talker:
    image: husarnet/husarnet
    volumes:
      - /var/lib/husarnet
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0 
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - HOSTNAME=talker-host
      - JOINCODE=${HUSARNET_JOINCODE}