# Quick Start
# $ docker compose -f compose.listener.yaml up

services:

  listener:
    build: .
    network_mode: service:husarnet-listener
    tty: true
    environment:
      - ROS_MASTER_URI=http://master:11311
      - ROS_IPV6=on
    command: rosrun roscpp_tutorials listener

  husarnet-listener:
    image: husarnet/husarnet
    volumes:
      - /var/lib/husarnet
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0 
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - HOSTNAME=listener-host
      - JOINCODE=${HUSARNET_JOINCODE}